//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsBrightnessControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RunOnStartUp {
            get {
                return ((bool)(this["RunOnStartUp"]));
            }
            set {
                this["RunOnStartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseHotKeys {
            get {
                return ((bool)(this["UseHotKeys"]));
            }
            set {
                this["UseHotKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SnappingInterval {
            get {
                return ((int)(this["SnappingInterval"]));
            }
            set {
                this["SnappingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SnapBrightness {
            get {
                return ((bool)(this["SnapBrightness"]));
            }
            set {
                this["SnapBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseMouseWheel {
            get {
                return ((bool)(this["UseMouseWheel"]));
            }
            set {
                this["UseMouseWheel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                    <HotKeyData xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
                        <Modifiers>Alt</Modifiers>
                        <Key>F10</Key>
                    </HotKeyData>
                ")]
        public global::HotKeyInputControlLibrary.HotKeyData IncreaseBrightnessHotKey {
            get {
                return ((global::HotKeyInputControlLibrary.HotKeyData)(this["IncreaseBrightnessHotKey"]));
            }
            set {
                this["IncreaseBrightnessHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                    <HotKeyData xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
                        <Modifiers>Alt</Modifiers>
                        <Key>F9</Key>
                    </HotKeyData>
                ")]
        public global::HotKeyInputControlLibrary.HotKeyData DecreaseBrightnessHotKey {
            get {
                return ((global::HotKeyInputControlLibrary.HotKeyData)(this["DecreaseBrightnessHotKey"]));
            }
            set {
                this["DecreaseBrightnessHotKey"] = value;
            }
        }
    }
}
